---
title: "RBC ROI Random Forest-Ridge Simulations (Structural)"
author: "Megan Jones"
date: "`r Sys.Date()`"
output:
  html_document: 
    code_folding: hide
    toc: true
    toc_float: true
    number_sections: true
    theme: spacelab
    highlight: haddock
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, eval = TRUE)
```

These simulations are for Figure 1.

In this simulation, $\xi$ is not equal to $\mu$, leading to 4 parameters.

$\xi$ is a random forest model from the build data.

$\mu$ is cross-validated ridge regression.


# Set up

```{r, eval=T}
# load libraries, data, and functions
source("/media/disk2/multivariateBWAS/RBC_sims/ROI_sims/sim_setup_roi_RBC.R")
library(ranger)
library(tuneRanger)
library(mlr)
library(dplyr)

# lambda grid for ridge regression
lambda_seq <- c(
  seq(10, 1, -1),        # From 10 to 1 (step of 1)
  seq(0.9, 0.1, -0.1),   # From 0.9 to 0.1 (step of 0.1)
  seq(0.09, 0.01, -0.01),# From 0.09 to 0.01 (step of 0.01)
  seq(0.009, 0.001, -0.001), # From 0.009 to 0.001 (step of 0.001)
  seq(0.0009, 0.0001, -0.0001), # From 0.0009 to 0.0001 (step of 0.0001)
  seq(0.00009, 0.00001, -0.00001), # From 0.00009 to 0.00001
  seq(0.000009, 0.000001, -0.000001), # From 0.000009 to 0.000001
  seq(0.0000009, 0.0000001, -0.0000001), # From 0.0000009 to 0.0000001
  0
)

rhos <- c(.10)
ns <- c(100, 200, 500, 750, 1000, 1500, 2000, 3000, 4000, 5000, 6000, 7500, 10000, 20000)

# set number of simulations
nsim = 500

RNGkind("L'Ecuyer-CMRG") # for reproducibility with pbmclapply
seed_table = data.frame(build = c(123, 435, 300, 789, 900), sim = c(029, 866, 999, 013, 456))


```


```{r}
# function to take phenotype, rho_true, seed index, arguments for sim function
perform_sim = function(pheno, rho_true, seed_ind, ncores, ...){
  #browser()
  
  # build model
  # cross-validated ridge regression
  keep_inds = which(!(is.na(build[,pheno])))
  
  
  # compare two competing models (random forest vs ridge regression)
  # True model will be generated from random forest
  # Second model will be ridge regression, which will have a lower vmu
  # can compute the true ceiling for both models
  
  # tune random forest
  # Combine predictors and outcome into one data.frame
  df = data.frame(build[keep_inds,"img"])
  df$pheno = build[keep_inds,pheno]
  # Create the regression task
  task = makeRegrTask(id = "rf_task", data = df, target = "pheno")
  rfTune = tuneRanger(task, num.trees = 250, iters = 25, iters.warmup = 10) # tune build model
  # save build parameters
  saveRDS(rfTune$recommended.pars, paste0(results_path, "rho_", rho_true*100,"/build_params.rds"))
  
  eval$fakeYMean = predict(rfTune$model, newdata = data.frame(eval$img))$data$response
  
  # calculate ridge model based on OLS
  # need to calculate target variance from the uniform distribution
  v_res = v_uniform(rho_true, var(eval$fakeYMean))
  rho_0 = cor_mu(eval$img, xi=eval$fakeYMean, lambda = 0, v_res = v_res)
  saveRDS(rho_0, paste0(results_path, "rho_", rho_true*100, "/rho_0.rds"))
  mu = get_mu(eval$img, xi=eval$fakeYMean, lambda=0)
  eval$mu = mu
  
  saveRDS(mu, paste0(results_path, "rho_", rho_true*100, "/mu.rds"))
  
  # save true difference and ratio
  D = rho_true - rho_0
  saveRDS(D, paste0(results_path, "rho_", rho_true*100,"/true_diff.rds"))
  saveRDS(exp(logit(rho_true^2) -logit(rho_0^2)), paste0(results_path, "rho_", rho_true*100,"/true_ratio.rds"))
  
  # for reproducibility using pbmclapply
  set.seed(seed_table$sim[seed_ind])
  mc.reset.stream()
  
  
  # for rho_2, fit a model outside of the simulations
  eval_train$fakeYMean = predict(rfTune$model, newdata = data.frame(eval_train$img))$data$response
  eval_test$fakeYMean = predict(rfTune$model, newdata = data.frame(eval_test$img))$data$response
  
  
  eval_train$fakeY = eval_train$fakeYMean + runif_target(nrow(eval_train), rho_true, var(eval$fakeYMean))
  muhat_tr_mod = cv.glmnet(x = eval_train$img, y = eval_train$fakeY, alpha = 0, lambda = lambda_seq)
  
  # for n = 2000 and rho = 0.1, perform a permutation test
  perm = rho_true == 0.1 & pheno %in% c("age")
  
  # for reproducibility using pbmclapply
  set.seed(seed_table$sim[seed_ind])
  mc.reset.stream()
  
  # perform sims
  sim_IF_4param(dt = eval, model_func = cv.glmnet, xi_name = "fakeYMean", ls_dist = NULL, res_mean = NULL,
         res_var = NULL, rho_2_test_dat = eval_test, ns = ns, nsim = nsim, K = 5, xname = "img",
         yname = "fakeY", model_args = list(alpha = 0, lambda = lambda_seq), types = all_types,
         cf_method = c("instant", "hold"), mu_name = "mu",
         save_path = paste0(results_path, "rho_", rho_true*100, "/n"), ncores = ncores, muhat_tr_mod = muhat_tr_mod, permute = perm, rho_true = rho_true)
}

v_uniform <- function(rho_true, v_xi){
  1/12 * (2*sqrt(3*(1/rho_true^2 - 1)*v_xi))^2
}

runif_target = function(n, rho_true, v_xi){
  runif(n, min = -sqrt(3*(1/rho_true^2 - 1)*v_xi), max = sqrt(3*(1/rho_true^2 - 1)*v_xi))
}
```



# Build

```{r, eval=T}
seed_ind = 2
results_path_root = "/media/disk2/multivariateBWAS/RBC_sims/ROI_sims/results/rfxi_ridgemu/"
# phenotypes to predict
#phenotypes = c("p_factor","age", "internal", "external")
phenotypes = c("age")
for(pheno in phenotypes){
  # set path for results
  results_path = paste0(results_path_root, pheno, "/")
  # create results subfolders if needed
  check_dirs(results_path, rhos, ns)
}

# save seed and atlas information
saveRDS(seed_ind, paste0(results_path_root, "seed_ind.rds"))
saveRDS(colnames(dat$img), paste0(results_path_root, "atlas.rds"))
set.seed(seed_table$build[seed_ind]) 

dat_split = split_model(dat)
build = dat_split$d1
eval = dat_split$d2

rm(dat)
rm(dat_split)

# for rho_2, cor_n(muhat_tr(X_te), Y_te | muhat_tr), need to define a model to apply as given
# split so that the training model uses 500 people
eval_split = split_model(eval, prop=(nrow(eval)-500)/(nrow(eval)))
eval_train = eval_split$d2
eval_test = eval_split$d1
rm(eval_split)
```

# Simulations



```{r}
#for (phen in c("p_factor", "age", "internal", "external")){
for(phen in "age"){
  for (rho in rhos){
    perform_sim(phen, rho, seed_ind, ncores = 40, results_path = paste0(results_path_root, phen, "/"))
  }
}


```


```{r, eval=F}
knitr::purl("/media/disk2/multivariateBWAS/RBC_sims/ROI_sims/ROI_rfxi_ridgemu.Rmd")
```
